package com.lionxxw.babasport.product.mapper;

import com.lionxxw.babasport.product.entity.ProductType;
import com.lionxxw.babasport.product.entity.ProductTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int countByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int deleteByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    List<ProductType> selectByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_type
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByPrimaryKey(ProductType record);
}