package com.lionxxw.babasport.product.mapper;

import com.lionxxw.babasport.product.entity.Size;
import com.lionxxw.babasport.product.entity.SizeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int countByExample(SizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int deleteByExample(SizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int insert(Size record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int insertSelective(Size record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    List<Size> selectByExample(SizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    Size selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") Size record, @Param("example") SizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByExample(@Param("record") Size record, @Param("example") SizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByPrimaryKeySelective(Size record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_size
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByPrimaryKey(Size record);
}