package com.lionxxw.babasport.core.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.no
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.weight
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.is_new
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.is_hot
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.is_commend
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isCommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.create_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.create_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.check_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.check_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String checkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.is_show
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.is_del
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.type_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.brand_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.keywords
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.sales
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.feature
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.color
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.size
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.id
     *
     * @return the value of bbs_product.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.id
     *
     * @param id the value for bbs_product.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.no
     *
     * @return the value of bbs_product.no
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.no
     *
     * @param no the value for bbs_product.no
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.name
     *
     * @return the value of bbs_product.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.name
     *
     * @param name the value for bbs_product.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.weight
     *
     * @return the value of bbs_product.weight
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.weight
     *
     * @param weight the value for bbs_product.weight
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.is_new
     *
     * @return the value of bbs_product.is_new
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.is_new
     *
     * @param isNew the value for bbs_product.is_new
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.is_hot
     *
     * @return the value of bbs_product.is_hot
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.is_hot
     *
     * @param isHot the value for bbs_product.is_hot
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.is_commend
     *
     * @return the value of bbs_product.is_commend
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsCommend() {
        return isCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.is_commend
     *
     * @param isCommend the value for bbs_product.is_commend
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsCommend(Boolean isCommend) {
        this.isCommend = isCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.create_time
     *
     * @return the value of bbs_product.create_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.create_time
     *
     * @param createTime the value for bbs_product.create_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.create_user_id
     *
     * @return the value of bbs_product.create_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.create_user_id
     *
     * @param createUserId the value for bbs_product.create_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.check_time
     *
     * @return the value of bbs_product.check_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.check_time
     *
     * @param checkTime the value for bbs_product.check_time
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.check_user_id
     *
     * @return the value of bbs_product.check_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.check_user_id
     *
     * @param checkUserId the value for bbs_product.check_user_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setCheckUserId(String checkUserId) {
        this.checkUserId = checkUserId == null ? null : checkUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.is_show
     *
     * @return the value of bbs_product.is_show
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.is_show
     *
     * @param isShow the value for bbs_product.is_show
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.is_del
     *
     * @return the value of bbs_product.is_del
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.is_del
     *
     * @param isDel the value for bbs_product.is_del
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.type_id
     *
     * @return the value of bbs_product.type_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.type_id
     *
     * @param typeId the value for bbs_product.type_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.brand_id
     *
     * @return the value of bbs_product.brand_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.brand_id
     *
     * @param brandId the value for bbs_product.brand_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.keywords
     *
     * @return the value of bbs_product.keywords
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.keywords
     *
     * @param keywords the value for bbs_product.keywords
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.sales
     *
     * @return the value of bbs_product.sales
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.sales
     *
     * @param sales the value for bbs_product.sales
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.feature
     *
     * @return the value of bbs_product.feature
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.feature
     *
     * @param feature the value for bbs_product.feature
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.color
     *
     * @return the value of bbs_product.color
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.color
     *
     * @param color the value for bbs_product.color
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.size
     *
     * @return the value of bbs_product.size
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.size
     *
     * @param size the value for bbs_product.size
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}