package com.lionxxw.babasport.core.entity;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.description
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_product.package_list
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String packageList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.description
     *
     * @return the value of bbs_product.description
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.description
     *
     * @param description the value for bbs_product.description
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_product.package_list
     *
     * @return the value of bbs_product.package_list
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getPackageList() {
        return packageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_product.package_list
     *
     * @param packageList the value for bbs_product.package_list
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setPackageList(String packageList) {
        this.packageList = packageList == null ? null : packageList.trim();
    }
}