package com.lionxxw.babasport.core.entity;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_type.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_type.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_type.parent_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_type.note
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_type.is_display
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isDisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_type.id
     *
     * @return the value of bbs_type.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_type.id
     *
     * @param id the value for bbs_type.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_type.name
     *
     * @return the value of bbs_type.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_type.name
     *
     * @param name the value for bbs_type.name
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_type.parent_id
     *
     * @return the value of bbs_type.parent_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_type.parent_id
     *
     * @param parentId the value for bbs_type.parent_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_type.note
     *
     * @return the value of bbs_type.note
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_type.note
     *
     * @param note the value for bbs_type.note
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_type.is_display
     *
     * @return the value of bbs_type.is_display
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_type.is_display
     *
     * @param isDisplay the value for bbs_type.is_display
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsDisplay(Boolean isDisplay) {
        this.isDisplay = isDisplay;
    }
}