package com.lionxxw.babasport.core.entity;

import java.util.Date;

public class Sku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.product_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.color_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer colorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.size_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer sizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.delive_fee
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Double deliveFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sku_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Double skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.stock_inventory
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer stockInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.stock_upper_limit
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer stockUpperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.location
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sku_img
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private String skuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sku_sort
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer skuSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sku_name
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.market_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.create_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.update_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.create_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.update_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.last_status
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer lastStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sku_type
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer skuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_sku.sales
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    private Integer sales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.id
     *
     * @return the value of bbs_sku.id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.id
     *
     * @param id the value for bbs_sku.id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.product_id
     *
     * @return the value of bbs_sku.product_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.product_id
     *
     * @param productId the value for bbs_sku.product_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.color_id
     *
     * @return the value of bbs_sku.color_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.color_id
     *
     * @param colorId the value for bbs_sku.color_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.size_id
     *
     * @return the value of bbs_sku.size_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.size_id
     *
     * @param sizeId the value for bbs_sku.size_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSizeId(Integer sizeId) {
        this.sizeId = sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.delive_fee
     *
     * @return the value of bbs_sku.delive_fee
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Double getDeliveFee() {
        return deliveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.delive_fee
     *
     * @param deliveFee the value for bbs_sku.delive_fee
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setDeliveFee(Double deliveFee) {
        this.deliveFee = deliveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sku_price
     *
     * @return the value of bbs_sku.sku_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Double getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sku_price
     *
     * @param skuPrice the value for bbs_sku.sku_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSkuPrice(Double skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.stock_inventory
     *
     * @return the value of bbs_sku.stock_inventory
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getStockInventory() {
        return stockInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.stock_inventory
     *
     * @param stockInventory the value for bbs_sku.stock_inventory
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setStockInventory(Integer stockInventory) {
        this.stockInventory = stockInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.stock_upper_limit
     *
     * @return the value of bbs_sku.stock_upper_limit
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getStockUpperLimit() {
        return stockUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.stock_upper_limit
     *
     * @param stockUpperLimit the value for bbs_sku.stock_upper_limit
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setStockUpperLimit(Integer stockUpperLimit) {
        this.stockUpperLimit = stockUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.location
     *
     * @return the value of bbs_sku.location
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.location
     *
     * @param location the value for bbs_sku.location
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sku_img
     *
     * @return the value of bbs_sku.sku_img
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public String getSkuImg() {
        return skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sku_img
     *
     * @param skuImg the value for bbs_sku.sku_img
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSkuImg(String skuImg) {
        this.skuImg = skuImg == null ? null : skuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sku_sort
     *
     * @return the value of bbs_sku.sku_sort
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getSkuSort() {
        return skuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sku_sort
     *
     * @param skuSort the value for bbs_sku.sku_sort
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSkuSort(Integer skuSort) {
        this.skuSort = skuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sku_name
     *
     * @return the value of bbs_sku.sku_name
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sku_name
     *
     * @param skuName the value for bbs_sku.sku_name
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.market_price
     *
     * @return the value of bbs_sku.market_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.market_price
     *
     * @param marketPrice the value for bbs_sku.market_price
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.create_time
     *
     * @return the value of bbs_sku.create_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.create_time
     *
     * @param createTime the value for bbs_sku.create_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.update_time
     *
     * @return the value of bbs_sku.update_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.update_time
     *
     * @param updateTime the value for bbs_sku.update_time
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.create_user_id
     *
     * @return the value of bbs_sku.create_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.create_user_id
     *
     * @param createUserId the value for bbs_sku.create_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.update_user_id
     *
     * @return the value of bbs_sku.update_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.update_user_id
     *
     * @param updateUserId the value for bbs_sku.update_user_id
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.last_status
     *
     * @return the value of bbs_sku.last_status
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getLastStatus() {
        return lastStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.last_status
     *
     * @param lastStatus the value for bbs_sku.last_status
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setLastStatus(Integer lastStatus) {
        this.lastStatus = lastStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sku_type
     *
     * @return the value of bbs_sku.sku_type
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sku_type
     *
     * @param skuType the value for bbs_sku.sku_type
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSkuType(Integer skuType) {
        this.skuType = skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_sku.sales
     *
     * @return the value of bbs_sku.sales
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_sku.sales
     *
     * @param sales the value for bbs_sku.sales
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }
}