package com.lionxxw.babasport.core.entity;

import java.util.Date;

public class TestTb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_tb.id
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_tb.name
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_tb.birthday
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_tb.id
     *
     * @return the value of test_tb.id
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_tb.id
     *
     * @param id the value for test_tb.id
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_tb.name
     *
     * @return the value of test_tb.name
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_tb.name
     *
     * @param name the value for test_tb.name
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_tb.birthday
     *
     * @return the value of test_tb.birthday
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_tb.birthday
     *
     * @param birthday the value for test_tb.birthday
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}