package com.lionxxw.babasport.user.mapper;

import com.lionxxw.babasport.user.entity.Buyer;
import com.lionxxw.babasport.user.entity.BuyerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int countByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int deleteByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    List<Buyer> selectByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    Buyer selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int updateByExample(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Mon Jun 13 13:07:26 CST 2016
     */
    int updateByPrimaryKey(Buyer record);
}