package com.lionxxw.babasport.country.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_province.id
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_province.code
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_province.name
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_province.id
     *
     * @return the value of bbs_province.id
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_province.id
     *
     * @param id the value for bbs_province.id
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_province.code
     *
     * @return the value of bbs_province.code
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_province.code
     *
     * @param code the value for bbs_province.code
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_province.name
     *
     * @return the value of bbs_province.name
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_province.name
     *
     * @param name the value for bbs_province.name
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}