package com.lionxxw.babasport.product.entity;

public class ProductImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_img.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_img.product_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_img.url
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_img.is_def
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    private Boolean isDef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_img.id
     *
     * @return the value of bbs_img.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_img.id
     *
     * @param id the value for bbs_img.id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_img.product_id
     *
     * @return the value of bbs_img.product_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_img.product_id
     *
     * @param productId the value for bbs_img.product_id
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_img.url
     *
     * @return the value of bbs_img.url
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_img.url
     *
     * @param url the value for bbs_img.url
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_img.is_def
     *
     * @return the value of bbs_img.is_def
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public Boolean getIsDef() {
        return isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_img.is_def
     *
     * @param isDef the value for bbs_img.is_def
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    public void setIsDef(Boolean isDef) {
        this.isDef = isDef;
    }
}