package com.lionxxw.babasport.user.entity;

import java.util.Date;

public class DeliveryAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.id
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.buyer
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String buyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.province
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.city
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.town
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.consignee
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.address
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.mobile
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.telephone
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.email
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.post_code
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.add_time
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.is_default
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.province_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.city_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_delivery_address.town_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    private String townName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.id
     *
     * @return the value of bbs_delivery_address.id
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.id
     *
     * @param id the value for bbs_delivery_address.id
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.buyer
     *
     * @return the value of bbs_delivery_address.buyer
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.buyer
     *
     * @param buyer the value for bbs_delivery_address.buyer
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.province
     *
     * @return the value of bbs_delivery_address.province
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.province
     *
     * @param province the value for bbs_delivery_address.province
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.city
     *
     * @return the value of bbs_delivery_address.city
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.city
     *
     * @param city the value for bbs_delivery_address.city
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.town
     *
     * @return the value of bbs_delivery_address.town
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.town
     *
     * @param town the value for bbs_delivery_address.town
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.consignee
     *
     * @return the value of bbs_delivery_address.consignee
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.consignee
     *
     * @param consignee the value for bbs_delivery_address.consignee
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.address
     *
     * @return the value of bbs_delivery_address.address
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.address
     *
     * @param address the value for bbs_delivery_address.address
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.mobile
     *
     * @return the value of bbs_delivery_address.mobile
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.mobile
     *
     * @param mobile the value for bbs_delivery_address.mobile
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.telephone
     *
     * @return the value of bbs_delivery_address.telephone
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.telephone
     *
     * @param telephone the value for bbs_delivery_address.telephone
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.email
     *
     * @return the value of bbs_delivery_address.email
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.email
     *
     * @param email the value for bbs_delivery_address.email
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.post_code
     *
     * @return the value of bbs_delivery_address.post_code
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.post_code
     *
     * @param postCode the value for bbs_delivery_address.post_code
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.add_time
     *
     * @return the value of bbs_delivery_address.add_time
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.add_time
     *
     * @param addTime the value for bbs_delivery_address.add_time
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.is_default
     *
     * @return the value of bbs_delivery_address.is_default
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.is_default
     *
     * @param isDefault the value for bbs_delivery_address.is_default
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.province_name
     *
     * @return the value of bbs_delivery_address.province_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.province_name
     *
     * @param provinceName the value for bbs_delivery_address.province_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.city_name
     *
     * @return the value of bbs_delivery_address.city_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.city_name
     *
     * @param cityName the value for bbs_delivery_address.city_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_delivery_address.town_name
     *
     * @return the value of bbs_delivery_address.town_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_delivery_address.town_name
     *
     * @param townName the value for bbs_delivery_address.town_name
     *
     * @mbggenerated Tue Jun 28 13:09:43 CST 2016
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }
}