package com.lionxxw.babasport.country.mapper;

import com.lionxxw.babasport.country.entity.City;
import com.lionxxw.babasport.country.entity.CityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_city
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKey(City record);
}