package com.lionxxw.babasport.country.mapper;

import com.lionxxw.babasport.country.entity.Province;
import com.lionxxw.babasport.country.entity.ProvinceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    Province selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_province
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKey(Province record);
}