package com.lionxxw.babasport.country.mapper;

import com.lionxxw.babasport.country.entity.Town;
import com.lionxxw.babasport.country.entity.TownExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int countByExample(TownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByExample(TownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insert(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int insertSelective(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    List<Town> selectByExample(TownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    Town selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") Town record, @Param("example") TownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByExample(@Param("record") Town record, @Param("example") TownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKeySelective(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_town
     *
     * @mbggenerated Sun Jun 19 19:39:58 CST 2016
     */
    int updateByPrimaryKey(Town record);
}