package com.lionxxw.babasport.core.mapper;

import com.lionxxw.babasport.core.entity.Color;
import com.lionxxw.babasport.core.entity.ColorExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int countByExample(ColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int deleteByExample(ColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int insert(Color record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int insertSelective(Color record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    List<Color> selectByExample(ColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    Color selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") Color record, @Param("example") ColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByExample(@Param("record") Color record, @Param("example") ColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByPrimaryKeySelective(Color record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_color
     *
     * @mbggenerated Thu Jun 02 10:24:11 CST 2016
     */
    int updateByPrimaryKey(Color record);
}