package com.lionxxw.babasport.core.mapper;

import com.lionxxw.babasport.core.entity.ProductImage;
import com.lionxxw.babasport.core.entity.ProductImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int countByExample(ProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int deleteByExample(ProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int insert(ProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int insertSelective(ProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    List<ProductImage> selectByExample(ProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    ProductImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductImage record, @Param("example") ProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByExample(@Param("record") ProductImage record, @Param("example") ProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByPrimaryKeySelective(ProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_img
     *
     * @mbggenerated Tue May 31 16:21:06 CST 2016
     */
    int updateByPrimaryKey(ProductImage record);
}