package com.lionxxw.babasport.core.mapper;

import com.lionxxw.babasport.core.entity.Sku;
import com.lionxxw.babasport.core.entity.SkuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Thu Jun 02 16:06:43 CST 2016
     */
    int updateByPrimaryKey(Sku record);
}