package com.lionxxw.babasport.core.mapper;

import com.lionxxw.babasport.core.entity.TestTb;
import com.lionxxw.babasport.core.entity.TestTbExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int countByExample(TestTbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int deleteByExample(TestTbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int insert(TestTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int insertSelective(TestTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    List<TestTb> selectByExample(TestTbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    TestTb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") TestTb record, @Param("example") TestTbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int updateByExample(@Param("record") TestTb record, @Param("example") TestTbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int updateByPrimaryKeySelective(TestTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_tb
     *
     * @mbggenerated Sat May 21 16:44:59 CST 2016
     */
    int updateByPrimaryKey(TestTb record);
}